import {db} from '../../config/firebase';
import {logger} from '../../config/chalk';

/** Adds data into a Firestore Document
 * @param {string} collection: Firestore collection name
 * @param {string} document: Firestore document name
 * @param {object} data: Data to insert
 */
async function addToDocument(
  collection: string,
  document: string,
  data: object
) {
  const res = await db
    .collection(collection)
    .doc(document)
    .set(data, {merge: true});
  logger.printLog({tag: `Updated `, log: data});
};

/** Adds data into an autogenerated Firestore Document in a
 * specified Firestore Collection
 * @param {string} collection: Firestore collection name
 * @param {object} data: Data to insert
 * @return {Promise<string>} docRef.id: The auto-generated Firestore Document Id
 */
async function addToCollection(
  collection: string,
  data: object
): Promise<string> {
  const docRef: FirebaseFirestore.DocumentReference = await db
    .collection(collection)
    .add(data);
  console.log('Added document with ID: ', docRef.id);
  return docRef.id;
};

export {addToDocument, addToCollection};
